### ISSUE TITLE
Make error, abstract class

### ISSUE THREAD

**Issue by NicoG60** [INdT/Quasi-Engine#30]
Try to build on mac os with Qt 5.10, i get this error : `src/scene.cpp:214:23: error: allocating an object of abstract class type 'Box2DDebugDraw'`
and also a warning :` src/fixture.h:32:1: warning: class 'b2FixtureDef' was previously declared as a struct here : Box2D/Dynamics/b2Fixture.h:56:8:`

**Comment by mdkcore0** [comment]
hi, thanks for contacting us!

all development of Quase-Engine was moved to [bacon2d](https://github.com/Bacon2D/Bacon2D/) ;)
